name: Build and upload to PyPI

on:
  workflow_dispatch:

jobs:
  build_sdist:
  name: Build sdist
  runs-on: ubuntu-20.04
  strategy:
    matrix:
      python-version: ['3.12']
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: python -m pip install -U pip 'setuptools>=45' 'setuptools-scm>=6.2'

    - name: Install build module
      run: pip install build

    - name: Debug: Show working directory and files
      run: |
        echo "PWD = $(pwd)"
        echo "=== Project root files ==="
        ls -al
        echo "=== setup.py content ==="
        cat setup.py || echo "setup.py not found"
        echo "=== pyproject.toml ==="
        cat pyproject.toml || echo "pyproject.toml not found"

    - name: Build sdist (with verbose)
      run: python -m build --sdist --verbose

    - uses: actions/upload-artifact@v4
      with:
        name: wheels-dist
        path: dist/*.tar.gz

  build_wheels:
    name: Build wheels
    needs: build_sdist
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        archs: ["x86_64, i686", "aarch64", "ppc64le", "s390x"]
        build: ["manylinux", "musllinux"]
        include:
          - os: windows-2022
            archs: "AMD64"
          - os: windows-2022
            archs: "x86"
          - os: windows-2022
            archs: "ARM64"
          - os: macos-13
            archs: "x86_64, arm64"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: runner.os == 'Linux'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_ARCHS: "${{ matrix.archs }}"
          CIBW_BUILD: "${{ matrix.build && '*-' || ''}}${{ matrix.build }}*"
          CIBW_PRERELEASE_PYTHONS: "${{ !startsWith(github.ref, 'refs/tags/v') }}"

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.build }}-${{ matrix.archs }}
          path: ./wheelhouse/*.whl

  upload_pypi:
    name: Upload to PyPI
    needs: [build_sdist, build_wheels]
    runs-on: ubuntu-20.04
    environment:
      name: pypi
      url: https://pypi.org/project/ctea/
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: sdist
          path: dist
          merge-multiple: true

      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
